export const fakeQuestions = [
    { id: 1, title: "What is React?", answer_details: "React is a JavaScript library for building user interfaces.", is_paid: true, is_featured: false, created_date: "2024-12-01" },
    { id: 2, title: "What is a component in React?", answer_details: "A component is a reusable piece of UI.", is_paid: false, is_featured: true, created_date: "2024-12-02" },
    { id: 3, title: "Explain useState Hook.", answer_details: "useState is a Hook that manages state in functional components.", is_paid: true, is_featured: true, created_date: "2024-12-03" },
    { id: 4, title: "What is JSX?", answer_details: "JSX is a syntax extension for JavaScript used with React to describe UI structure.", is_paid: true, is_featured: false, created_date: "2024-12-04" },
    { id: 5, title: "What is the Virtual DOM?", answer_details: "The Virtual DOM is a lightweight representation of the real DOM used by React.", is_paid: false, is_featured: true, created_date: "2024-12-05" },
    { id: 6, title: "Explain React Props.", answer_details: "Props are inputs to components that allow data to be passed between components.", is_paid: true, is_featured: false, created_date: "2024-12-06" },
    { id: 7, title: "What is Redux?", answer_details: "Redux is a state management library often used with React applications.", is_paid: false, is_featured: true, created_date: "2024-12-07" },
    { id: 8, title: "What is useEffect Hook?", answer_details: "useEffect is a Hook that allows side effects in functional components.", is_paid: true, is_featured: true, created_date: "2024-12-08" },
    { id: 9, title: "Explain React Context.", answer_details: "React Context provides a way to pass data through the component tree without props.", is_paid: false, is_featured: false, created_date: "2024-12-09" },
    { id: 10, title: "What is a key in React?", answer_details: "A key is a unique identifier for elements in lists.", is_paid: true, is_featured: true, created_date: "2024-12-10" },
    { id: 11, title: "What are React Portals?", answer_details: "React Portals allow rendering children into a DOM node outside of their parent.", is_paid: false, is_featured: false, created_date: "2024-12-11" },
    { id: 12, title: "What is lazy loading in React?", answer_details: "Lazy loading delays the loading of components until they are needed.", is_paid: true, is_featured: false, created_date: "2024-12-12" },
    { id: 13, title: "What are React fragments?", answer_details: "Fragments let you group multiple elements without adding extra nodes.", is_paid: false, is_featured: true, created_date: "2024-12-13" },
    { id: 14, title: "Explain React.memo.", answer_details: "React.memo is a higher-order component that prevents unnecessary re-renders.", is_paid: true, is_featured: true, created_date: "2024-12-14" },
    { id: 15, title: "What is server-side rendering (SSR)?", answer_details: "SSR renders components on the server before sending HTML to the client.", is_paid: false, is_featured: true, created_date: "2024-12-15" },
    { id: 16, title: "What is the difference between class and functional components?", answer_details: "Class components use ES6 classes; functional components are functions.", is_paid: true, is_featured: false, created_date: "2024-12-16" },
    { id: 17, title: "What is a higher-order component (HOC)?", answer_details: "An HOC is a function that takes a component and returns a new component.", is_paid: false, is_featured: true, created_date: "2024-12-17" },
    { id: 18, title: "Explain React Refs.", answer_details: "Refs provide a way to access and interact with DOM nodes.", is_paid: true, is_featured: false, created_date: "2024-12-18" },
    { id: 19, title: "What is Prop Drilling?", answer_details: "Prop Drilling is passing props through multiple levels of components.", is_paid: false, is_featured: false, created_date: "2024-12-19" },
    { id: 20, title: "What is a React Hook?", answer_details: "Hooks are functions that let you use React features in functional components.", is_paid: true, is_featured: true, created_date: "2024-12-20" },
    { id: 21, title: "What is the purpose of React keys?", answer_details: "Keys help React identify which items have changed in a list.", is_paid: false, is_featured: false, created_date: "2024-12-21" },
    { id: 22, title: "What are controlled components in React?", answer_details: "Controlled components have their state controlled by React.", is_paid: true, is_featured: true, created_date: "2024-12-22" },
    { id: 23, title: "What is React Router?", answer_details: "React Router is a library for routing in React applications.", is_paid: false, is_featured: false, created_date: "2024-12-23" },
    { id: 24, title: "What are synthetic events in React?", answer_details: "Synthetic events are React's wrapper around native browser events.", is_paid: true, is_featured: false, created_date: "2024-12-24" },
    { id: 25, title: "What is React StrictMode?", answer_details: "StrictMode highlights potential issues in an application.", is_paid: false, is_featured: true, created_date: "2024-12-25" },
    { id: 26, title: "What is code splitting in React?", answer_details: "Code splitting reduces bundle size by splitting code into smaller chunks.", is_paid: true, is_featured: true, created_date: "2024-12-26" },
    { id: 27, title: "What is the difference between state and props?", answer_details: "State is local to a component; props are passed from parent to child.", is_paid: false, is_featured: true, created_date: "2024-12-27" },
    { id: 28, title: "What are pure components in React?", answer_details: "Pure components avoid unnecessary re-renders by using shallow comparisons.", is_paid: true, is_featured: false, created_date: "2024-12-28" },
    { id: 29, title: "What is the useReducer Hook?", answer_details: "useReducer is a Hook for managing complex state logic.", is_paid: false, is_featured: true, created_date: "2024-12-29" },
    { id: 30, title: "What is state lifting in React?", answer_details: "State lifting is moving state up to a common ancestor component.", is_paid: true, is_featured: false, created_date: "2024-12-30" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
    { id: 31, title: "Explain the useContext Hook.", answer_details: "useContext lets components consume data from a React Context.", is_paid: false, is_featured: true, created_date: "2024-12-31" },
];
